#!/usr/bin/env bash
CMD="$1"
case "$CMD" in
  test)
    busted --pattern="test_.*%.lua" tests
    ;;
  build)
    ./scripts/build.sh
    ;;
  copy)
    ./scripts/cp.sh
    ;;
  *)
    echo "Usage: ./cmdsage [test|build|copy]"
    exit 1
    ;;
esac
