print("loader.lua start.")

require("Core.CommandSage_Config")
require("Core.CommandSage_Core")
require("Core.CommandSage_Discovery")

require("Modules.CommandSage_Trie")
require("Modules.CommandSage_FuzzyMatch")
require("Modules.CommandSage_ParameterHelper")
require("Modules.CommandSage_AdaptiveLearning")
require("Modules.CommandSage_PersistentTrie")
require("Modules.CommandSage_Tutorial")
require("Modules.CommandSage_Performance")
require("Modules.CommandSage_SecureCallback")
require("Modules.CommandSage_Fallback")
require("Modules.CommandSage_CommandOrganizer")
require("Modules.CommandSage_AutoType")
require("Modules.CommandSage_HistoryPlayback")
require("Modules.CommandSage_DeveloperAPI")
require("Modules.CommandSage_UIAccessibility")
require("Modules.CommandSage_Analytics")
require("Modules.CommandSage_MultiModal")
require("Modules.CommandSage_AROverlays")
require("Modules.CommandSage_AutoComplete")
require("Modules.CommandSage_Terminal")
require("Modules.CommandSage_ShellContext")
require("Modules.CommandSage_Licensing")
require("Modules.CommandSage_ConfigGUI")
require("Modules.CommandSage_KeyBlocker")

print("loader.lua: finished loading in .toc order.")
