describe("Integration: multiple modules working together can do something that requires both the Trie and FuzzyMatch", function()
    it("should insert a slash into the Trie and fuzzy-match it", function()
        CommandSage_Trie:InsertCommand("/dance", {desc="dance test"})
        local possible = CommandSage_Trie:AllCommands()
        local results = CommandSage_FuzzyMatch:GetSuggestions("/danc", possible)
        assert.is_true(#results > 0)
        assert.equals("/dance", results[1].slash)
    end)
end)
