name: Build CommandSage

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install zip
        run: sudo apt-get install zip
      - name: Build
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CommandSage-Zip
          path: ./dist/*.zip

      # Example step for auto-publishing to CurseForge (requires a real action or custom script)
      # - name: Publish to CurseForge
      #   run: echo "Would upload to CurseForge with ${{ secrets.CURSEFORGE_TOKEN }}..."
